- id: go-lint
  name: go lint
  files: \.go$
  entry: go-lint.sh
  language: script
  description: "Runs `golint`, install it with `go get -u github.com/golang/lint/golint`."
- id: go-vet
  name: go vet
  files: \.go$
  entry: go-vet.sh
  language: script
  description: "Runs `go vet`, requires Golang."
- id: go-fmt
  name: go fmt
  files: \.go$
  entry: go-fmt.sh
  language: script
  description: "Runs `gofmt`, requires Golang."
- id: go-metalinter
  name: Go Meta Linter
  files: \.go$
  entry: go-metalinter.sh
  language: script
  description: "Runs a bunch of Go linters, requires https://github.com/alecthomas/gometalinter."
